# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and yarn.lock files to the working directory
COPY package.json yarn.lock ./
COPY tsconfig.json .

# Install the application dependencies with yarn
RUN yarn

# Copy the rest of the application code to the working directory
COPY . .

RUN yarn build

# Expose port 8080 to the outside world
EXPOSE 8080

# Define the command to start the application
CMD ["yarn", "start"]
