name: BACKEND - Build and test

on:
  push:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn install

      - name: install typescript
        run: yarn add typescript

      - name: Build Application
        run: yarn build
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          MONGO_DB_USER_NAME: ${{ secrets.MONGO_DB_USER_NAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
          TICKETMASTER_API_URL: ${{ secrets.TICKETMASTER_API_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_API_URL: ${{ secrets.GOOGLE_API_URL }}
          GOOGLE_API_DIRECTION_URL: ${{ secrets.GOOGLE_API_DIRECTION_URL }}
          GOOGLE_API_PLACE_DETAILS_URL: ${{ secrets.GOOGLE_API_PLACE_DETAILS_URL }}
          PORT: ${{ secrets.PORT }}
  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          MONGO_DB_USER_NAME: ${{ secrets.MONGO_DB_USER_NAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
          TICKETMASTER_API_URL: ${{ secrets.TICKETMASTER_API_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_API_URL: ${{ secrets.GOOGLE_API_URL }}
          GOOGLE_API_DIRECTION_URL: ${{ secrets.GOOGLE_API_DIRECTION_URL }}
          GOOGLE_API_PLACE_DETAILS_URL: ${{ secrets.GOOGLE_API_PLACE_DETAILS_URL }}
          PORT: ${{ secrets.PORT }}
