name: FRONTEND - Build - Test - Deploy 

on:
  push:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_GOOGLE_MAP_API_KEY: ${{ secrets.VITE_GOOGLE_MAP_API_KEY }}
          VITE_GOOGLE_PHOTO_REFERENCE: ${{ secrets.VITE_GOOGLE_PHOTO_REFERENCE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_GOOGLE_MAP_API_KEY: ${{ secrets.VITE_GOOGLE_MAP_API_KEY }}
          VITE_GOOGLE_PHOTO_REFERENCE: ${{ secrets.VITE_GOOGLE_PHOTO_REFERENCE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_STRIPE_KEY: ${{ secrets.VITE_STRIPE_KEY }}

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    needs: test
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn install
      - name: Build Application
        run: yarn build
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: Deploy
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_GOOGLE_MAP_API_KEY: ${{ secrets.VITE_GOOGLE_MAP_API_KEY }}
          VITE_GOOGLE_PHOTO_REFERENCE: ${{ secrets.VITE_GOOGLE_PHOTO_REFERENCE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_STRIPE_KEY: ${{ secrets.VITE_STRIPE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}